---
- name: Install HTTP server
  hosts: gp3
  become: yes

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"

    - name: Start HTTPD
      service:
        name: httpd
        state: started
      when: ansible_distribution == "Amazon"

    - name: Enable HTTPD
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "Amazon"

    - name: Install Apache2 on Ubuntu
      apt:
        update_cache: yes
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start Apache2 on Ubuntu
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Enable Apache2 on Ubuntu
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache2 on Debian
      apt:
        update_cache: yes
        name: apache2
        state: present
      when: ansible_distribution == "Debian"

    - name: Start Apache2 on Debian
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Debian"

    - name: Enable Apache2 on Debian
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Debian"
    
    - name: Install Nginx on Fedora
      dnf:
        name: nginx
        state: present
      when: ansible_distribution == "Fedora"

    - name: Start Nginx on Fedora
      service:
        name: nginx
        state: started
      when: ansible_distribution == "Fedora"

    - name: Enable Nginx on Fedora
      service:
        name: nginx
        enabled: yes
      when: ansible_distribution == "Fedora"


...